name: zapizapi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  fluttertoast: ^9.0.0
  supabase_flutter: ^2.10.2
  very_good_analysis: ^10.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logos/logo_login.png
    - assets/icons/ic_pen-new-square-broken.svg
    - assets/icons/ic-menu-dots-circle-broken.svg
    - .env
  uses-material-design: true
